"""
Export YouTube cookies from Chrome to cookies.txt for yt-dlp.
Uses nodriver (already installed) to launch a Chrome instance.

IMPORTANT: Close all Chrome windows before running this script!
After running, a Chrome window will open. Log into YouTube if needed,
then press Enter in the terminal to export cookies and close Chrome.
"""
import asyncio
import sys
import os
import time

async def main():
    try:
        import nodriver as uc
    except ImportError:
        print("ERROR: nodriver not installed. Run: pip install nodriver")
        sys.exit(1)

    print("Launching Chrome... (make sure all other Chrome windows are closed)")
    print()

    browser = await uc.start(
        headless=False,
        browser_args=[
            "--no-first-run",
            "--no-default-browser-check",
        ]
    )

    # Navigate to YouTube
    page = await browser.get("https://www.youtube.com")
    print("YouTube loaded. If you see a 'Sign in' prompt or bot check:")
    print("  1. Sign into your Google account in the browser window")
    print("  2. Make sure you can see the YouTube homepage normally")
    print()
    input("Press ENTER here after YouTube is loaded and you're signed in...")

    # Get all cookies
    cookies = await page.send(uc.cdp.network.get_all_cookies())

    # Filter YouTube/Google cookies
    youtube_domains = ['.youtube.com', '.google.com', '.googleapis.com', 'youtube.com', 'google.com']
    yt_cookies = []
    for cookie in cookies:
        domain = cookie.domain
        if any(d in domain for d in youtube_domains):
            yt_cookies.append(cookie)

    if not yt_cookies:
        print("WARNING: No YouTube cookies found!")
        browser.stop()
        sys.exit(1)

    # Write Netscape cookies.txt format
    output_path = os.path.join(os.path.dirname(os.path.abspath(__file__)), "cookies.txt")
    with open(output_path, "w") as f:
        f.write("# Netscape HTTP Cookie File\n")
        f.write("# This file was generated by get_cookies.py\n\n")
        for cookie in yt_cookies:
            domain = cookie.domain
            flag = "TRUE" if domain.startswith(".") else "FALSE"
            path = cookie.path or "/"
            secure = "TRUE" if cookie.secure else "FALSE"
            expires = int(cookie.expires) if cookie.expires and cookie.expires > 0 else 0
            name = cookie.name
            value = cookie.value
            f.write(f"{domain}\t{flag}\t{path}\t{secure}\t{expires}\t{name}\t{value}\n")

    print(f"\nExported {len(yt_cookies)} YouTube cookies to: {output_path}")
    print("You can now close this window. The import should work with these cookies.")

    browser.stop()

if __name__ == "__main__":
    asyncio.run(main())
